CREATE DATABASE GestionEmpleadosBD

CREATE TABLE PERSONAEx(
IDPERSONA INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDPERSONA),
);
CREATE TABLE EMPLEADOEx(
IDEMPLEADO INT IDENTITY (1,1) NOT NULL,
IDPERSONA INT NOT NULL,
PUESTO NVARCHAR (50) NOT NULL,
SALARIO NVARCHAR (50) NOT NULL,
FECHACONTRATACION DATETIME NOT NULL,
PRIMARY KEY (IDEMPLEADO),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONAEx (IDPERSONA)
);
